version: '3'
services:
  bhojpur.net:
    image: "docker.pkg.github.com/bhojpur/bhojpur.net/bhojpur.net:latest"
    build:
      context: .
      args:
        - VUE_APP_URL=ws://localhost:8080
    environment:
      - PORT=80
    ports:
      - "80:80"
  suga:
    image: "docker.pkg.github.com/bhojpur/suga/suga:latest"
    environment:
      - PORT=8080
    ports:
      - "8080:8080"